version: '3'

services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    command: /bin/bash -c "influxd & sleep 5 && influx -execute 'CREATE DATABASE RYU' && tail -f /dev/null"

  telegraf:
    image: telegraf
    depends_on:
      - influxdb
    ports:
      - "8094:8094/udp"  # Ryu sends metrics here
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro  # Read-only mount

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
